#!/bin/bash

echo "export TURTLEBOT_BASE=kobuki" >> ~/.bashrc
echo "export TURTLEBOT_STACKS=hexagons" >> ~/.bashrc
echo "export TURTLEBOT_3D_SENSOR=kinect" >> ~/.bashrc
echo "export TURTLEBOT_SIMULATION=false" >> ~/.bashrc
echo "export TURTLEBOT_BATTERY=/proc/acpi/battery/BAT0" >> ~/.bashrc
echo "export TURTLEBOT_SERIAL_PORT=/dev/kobuki" >> ~/.bashrc

sudo cp ./60-kobuki.rules /etc/udev/rules.d
sudo service udev reload
sleep 2
sudo service udev restart
